EnvironmentRequirements:
  CERN_ROOT:
    required: true
    version: ">=6.22"
    get_path_command: "root-config --prefix"
    Dependencies:
    - name: minuit2
      required: true
      check_command: "root-config --has-minuit2"
      expected_output: "yes"

  Python:
    version: ">=3.10"
    Dependencies:
    - name: numpy 
      required: true 
      version: ">=1.18.0"
    - name: scipy
      required: true 
      version: ">=1.4.0"
    - name: pyyaml
      required: true
      version: ">=5.1"
    - name: dynesty
      required: true
      version: ">=2.1.0"
    - name: h5py
      required: true
      version: ">=3.10"
    - name: pandas
      required: true
      version: ">=3.10"
    - name: matplotlib
      required: true
      version: ">=3.3"
    - name: pyhf
      required: true
      version: ">=0.7"

      
